- hosts: webservers

  tasks:
    - name: delete nginx
      ansible.builtin.apt:
        name: nginx
        state: absent
      become: yes

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes
