- hosts: webservers

  tasks:
    - name: install pip
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: yes
      become: yes

    - name: delete pip
      ansible.builtin.apt:
        name: pip
        state: absent
      become: yes
