- hosts: webservers

  tasks:
    - name: apt cache update
      ansible.builtin.apt:
        update_cache: yes
      become: yes
      tags: system

    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
      become: yes
      tags: packages

    - name: install tmux
      ansible.builtin.apt:
        name: tmux
        state: present
      become: yes
      tags: packages

    - name: install Nodejs
      ansible.builtin.apt:
        name: nodejs
        state: present
      become: yes
      tags: packages

    - name: make user sansa
      user:
        name: sansa
        uid: 200
        shell: /bin/bash
      become: yes
      tags: system
